sudo: required
services:
  - docker

before_install: 
  - docker build -t akshaylilac/docker-react-deployment -f Dockerfile.dev .

script: 
  - docker run akshaylilac/docker-react-deployment npm run test -- --coverage
  